id: AEC84BEEF
title: Prayer of Aspiration Incorporating the Eight Thoughts of Great Beings Who Follow
  the Way of the Mahāyāna
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:33:27.819784
  last_modified_at: 2022-03-01 00:33:27.819796
